on: [push, pull_request]
name: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: 'x64'
          distribution: 'full'
          version: 'current'
      - run: raco pkg install --auto lsl-lib/ lsl/
      - run: xvfb-run -a raco test --drdr lsl/
